// LOCALHOST
### Get all temples
GET http://localhost:1001/temples

### Get temple by id
GET http://localhost:1001/temples/65b5078283e854f3af04d632

### Create temple
POST http://localhost:1001/temples HTTP/1.1
content-type: application/json

{
    "name":"Nauvoo Temple",
    "status":"Destroyed",
    "location":"Nauvoo",
    "dedication":"05/01/1846"
}

### PUT temple
PUT http://localhost:1001/temples/65b5078283e854f3af04d632 HTTP/1.1
content-type: application/json

{
    "name": "Nauvoo Temple",
    "status": "Destroyed",
    "location": "Nauvo",
    "dedication": "05/01/1846"  
}

### DELETE temple
DELETE http://localhost:1001/temples/65b5078283e854f3af04d632 HTTP/1.1


### Get all Presidents
GET http://localhost:1001/presidents


### Get President by id
GET http://localhost:1001/presidents/65b4f41159aa3d206d8b651e


### Create President
POST http://localhost:1001/presidents HTTP/1.1
content-type: application/json

{
    "birth":"any",
    "placeOfBirth":"any",
    "ordination":"any",
    "death":"any",
    "lenght": "any",
    "firstName": "any",
    "lastName": "any"

}

### PUT President
PUT http://localhost:1001/presidents/65b4f41159aa3d206d8b651e HTTP/1.1
content-type: application/json

{
   "birth":"any",
    "placeOfBirth":"any",
    "ordination":"any",
    "death":"any",
    "lenght": "any",
    "firstName": "any",
    "lastName": "any"
}

### DELETE temple
DELETE http://localhost:1001/presidents/65bcdd2f8b350ba216a9e141 HTTP/1.1

// PRODUCTION

### Get all temples
GET https://jucinaldoduarte-cse-341-project-2.onrender.com:1001/temples

### Get temple by id
GET https://jucinaldoduarte-cse-341-project-2.onrender.com:1001/temples/65b5078283e854f3af04d632

### Create temple
POST https://jucinaldoduarte-cse-341-project-2.onrender.com:1001/temples HTTP/1.1
content-type: application/json

{
    "name":"Nauvoo Temple",
    "status":"Destroyed",
    "location":"Nauvoo",
    "dedication":"05/01/1846"
}

### PUT temple
PUT https://jucinaldoduarte-cse-341-project-2.onrender.com:1001/temples/65b51b97e561b01c4e0ac4d6 HTTP/1.1
content-type: application/json

{
    "name": "Nauvoo Temple",
    "status": "Destroyed",
    "location": "Nauvo",
    "dedication": "05/01/1846"  
}

### DELETE temple
DELETE https://jucinaldoduarte-cse-341-project-2.onrender.com:1001/temples/65b51b97e561b01c4e0ac4d6  HTTP/1.1


### Get all Presidents
GET https://jucinaldoduarte-cse-341-project-2.onrender.com:1001/presidents


### Get President by id
GET https://jucinaldoduarte-cse-341-project-2.onrender.com:1001/65b4f41159aa3d206d8b651e

### Create President
POST https://jucinaldoduarte-cse-341-project-2.onrender.com:1001/presidents HTTP/1.1
content-type: application/json

{
    "birth":"any",
    "placeOfBirth":"any",
    "ordination":"any",
    "death":"any",
    "lenght": "any",
    "firstName": "any",
    "lastName": "any"

}

### PUT President
PUT https://jucinaldoduarte-cse-341-project-2.onrender.com:1001/presidents/65bcdd2f8b350ba216a9e141 HTTP/1.1
content-type: application/json

{
   "birth":"any",
    "placeOfBirth":"any",
    "ordination":"any",
    "death":"any",
    "lenght": "any",
    "firstName": "any",
    "lastName": "any"
}

### DELETE temple
DELETE https://jucinaldoduarte-cse-341-project-2.onrender.com:1001/presidents/65bcdd2f8b350ba216a9e141 HTTP/1.1


